-- LOT_WIP：10000 筆，TYPE_FLAG 奇偶交替
INSERT INTO LOT_WIP
SELECT
    'LOT' || LPAD(CAST(x AS VARCHAR), 5, '0') || '.W01',
    CASE WHEN MOD(x, 2) = 0 THEN 'A' ELSE 'B' END
FROM SYSTEM_RANGE(1, 10000);

-- CP_WFRYLD：WAFER_ID = LOT 前段 + '01'，END_TEST_TIME 分散在過去 0~10 小時內
INSERT INTO CP_WFRYLD
SELECT
    'LOT' || LPAD(CAST(x AS VARCHAR), 5, '0') || '.01',
    CASE WHEN MOD(x, 2) = 0 THEN 'A' ELSE 'B' END,
    DATEADD('MINUTE', -(MOD(x * 37, 600) + 10), NOW()),
    1
FROM SYSTEM_RANGE(1, 10000);

-- WAFER_SUM：
--   ALL_INSP_DT / SAMPLE_INSP_DT 交替使用（模擬真實資料混合狀況）
--   每 20 筆其中 1 筆 WAIVE_INSP_FLAG='Y'（應被 WHERE 過濾掉）
INSERT INTO WAFER_SUM
SELECT
    'LOT' || LPAD(CAST(x AS VARCHAR), 5, '0') || '.W01',
    'CASE_' || LPAD(CAST(x AS VARCHAR), 5, '0'),
    'W01.01',
    CASE WHEN MOD(x, 2) = 0 THEN DATEADD('MINUTE', -(MOD(x * 13, 300)), NOW()) ELSE NULL END,
    CASE WHEN MOD(x, 2) != 0 THEN DATEADD('MINUTE', -(MOD(x * 13, 300)), NOW()) ELSE NULL END,
    CASE WHEN MOD(x, 20) = 0 THEN 'Y' ELSE 'N' END
FROM SYSTEM_RANGE(1, 10000);
