DROP TABLE IF EXISTS WAFER_SUM;
DROP TABLE IF EXISTS LOT_WIP;
DROP TABLE IF EXISTS CP_WFRYLD;

CREATE TABLE WAFER_SUM (
    LOT_ID          VARCHAR(50)  NOT NULL,
    CASE_ID         VARCHAR(50)  NOT NULL,
    WAFER_ID        VARCHAR(50)  NOT NULL,
    ALL_INSP_DT     TIMESTAMP,
    SAMPLE_INSP_DT  TIMESTAMP,
    WAIVE_INSP_FLAG VARCHAR(1)   DEFAULT 'N',
    PRIMARY KEY (LOT_ID, CASE_ID, WAFER_ID)
);

CREATE TABLE LOT_WIP (
    LOT_ID    VARCHAR(50) NOT NULL,
    TYPE_FLAG VARCHAR(10),
    PRIMARY KEY (LOT_ID)
);

CREATE TABLE CP_WFRYLD (
    WAFER_ID      VARCHAR(50) NOT NULL,
    TYPE_FLAG     VARCHAR(10),
    END_TEST_TIME TIMESTAMP,
    SORT_NO       INT,
    PRIMARY KEY (WAFER_ID, TYPE_FLAG)
);
